"""build.py: writes infographic/crudebuster_hitboxes_and_ai.html from the ROM tables and the box captures.

Inputs (all regenerated by this script or named in infographic/README.md):
  enemies1/py/brain_probs.py   exact next-state distributions of the shared brain $2438a (decoded from the ROM)
  enemies1/py/cdamage.py       damage per pool C type and difficulty ($fd2a, $fcca, $fd5a, $fd8a)
  py/overlay.py captures       assets/box_*.png, made from scratchpad/crudebuster/nb_cap/cap*.ram + the matching screenshots
  NATURAL                      the natural-play table below (player/natural.md has the evidence)
Usage: python py/build.py     (from reversing/crudebuster/infographic, with M68000/.venv)"""
import base64, html, io, json, os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.abspath(os.path.join(HERE, ".."))
CB = os.path.abspath(os.path.join(BASE, ".."))
sys.path.insert(0, os.path.join(CB, "enemies1/py"))
import brain_probs as B
from PIL import Image

# ---------------------------------------------------------------- data
TYPES = [  # (type, name, where, hp), names are descriptions of sprites (enemies1.md, the game prints none)
    (3, "Bruiser", "levels 1-2", None),
    (5, "Jet-pack cyborg", "levels 1-2", None),
    (9, "Armoured cyborg", "level 0 mid-boss", 16),
    (11, "Strongman", "level 2 mid-boss", 32),
]
GROUP = {"wait": "wait", 6: "wait", 7: "approach", 8: "approach", 9: "reposition", 10: "reposition"}
def group(state):
    if isinstance(state, str):
        if state == "wait": return "wait"
        n = int(state.rstrip("*"), 16)
    else: n = state
    return GROUP.get(n, "attack")
GCOL = ["wait", "approach", "reposition", "attack"]
GLABEL = {"wait": "idle (6)", "approach": "walk toward you (7, 8)", "reposition": "jump to your lane / drop (9, a)", "attack": "attack or special (b and up, type-specific)"}

def brain_rows():
    out = []
    for t, name, where, hp in TYPES:
        s = B.summarise(t)
        rows = {}
        for case in "ABC":
            cells = []
            for b in range(16):
                d, gated = s[case][b]
                g = {k: 0.0 for k in GCOL}
                detail = []
                for st, pr in sorted(d.items(), key=lambda kv: -kv[1]):
                    g[group(st)] += pr
                    detail.append(("%s" % (("state $%s" % st) if st != "wait" else "no change")) + " %d%%" % round(pr * 100))
                cells.append(dict(b=b, g=g, gated=gated, detail=detail))
            rows[case] = cells
        out.append(dict(type=t, name=name, where=where, hp=hp, rows=rows))
    return out

def damage_table():
    txt = subprocess.run([sys.executable, os.path.join(CB, "enemies1/py/cdamage.py")], capture_output=True, text=True, check=True).stdout
    rows = []
    for ln in txt.splitlines():
        p = ln.split()
        if len(p) >= 9 and p[0].startswith("C"):
            rows.append(dict(c=int(p[0][1:]), normal=int(p[2]), easy=int(p[4]), hard=int(p[6]), hardest=int(p[8])))
    return rows

MOVES = [  # name, (R, L, B, T), active frames, note   (player.md "Move table"; boxes verified with py/boxes.py and py/atkbox.py)
    ("Jab", (40, 0, -8, -32), "frames 6-11", "first and second hit of the chain"),
    ("Jab finisher, tall", (24, 0, -8, -64), "frames 36-41", "variant 1 of the third hit"),
    ("Jab finisher, long", (40, 0, 0, -40), "frames 36-41", "variant 2 of the third hit"),
    ("Walking jab", (40, 8, 16, -16), "frames 6-11", "low variant; the player stops during it"),
    ("Turn-around kick", (40, 0, 16, -32), "frames 8-23", "b1 while facing away from the last direction"),
    ("Jump kick", (40, 8, 32, 0), "until landing", "b1 in the air; hits things below head height"),
    ("Weapon swing", (40, 8, 16, -16), "frames 6-11", "b1 while carrying a board or pipe"),
    ("Grab", (36, 16, -8, -16), "frames 8-15", "pick-up box, not a damage box"),
]
BODY = (7, -8, 31, -32)  # R, L, B, T of the standing body box (live: record +64..70 minus x, y)

BOSSES = [  # name, where, hp in jabs, source
    ("Armoured cyborg", "level 0 mid", 16, "enemies1 4.1, lab"),
    ("Spiked roller", "level 1 mid", 16, "enemies1 4.2, lab"),
    ("Statue boss", "level 0 end", 24, "enemies1 4.1, nat"),
    ("Gang leader", "level 1 end", 24, "enemies1 4.2, lab"),
    ("Horned mutant", "level 4 end", 30, "enemies2 6.2, injected run"),
    ("Strongman", "level 2 mid", 32, "enemies1 4.3, lab"),
    ("Ape (after the champion)", "level 3 end", 48, "enemies2 6.2: 0x11 at 48 turns into the ape at 32"),
]

NATURAL = json.load(open(os.path.join(BASE, "natural.json"))) if os.path.exists(os.path.join(BASE, "natural.json")) else []

# ---------------------------------------------------------------- images
def embed(name, colors=96):
    im = Image.open(os.path.join(BASE, "assets", name)).convert("RGB")
    im = im.quantize(colors=colors, method=Image.Quantize.MEDIANCUT)
    bio = io.BytesIO(); im.save(bio, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(bio.getvalue()).decode()

# ---------------------------------------------------------------- svg pieces
def esc(s): return html.escape(str(s), quote=True)

def moves_svg():
    k = 2.0; cw, ch = 190, 282; cols = 4
    x0u, y0u = -16, -72  # world units of the cell's top-left
    out = []
    for i, (name, (R, L, Bb, T), act, note) in enumerate(MOVES):
        cx, cy = (i % cols) * cw, (i // cols) * ch
        def X(u): return cx + (u - x0u) * k + 6
        def Y(v): return cy + (v - y0u) * k + 6
        grab = name == "Grab"
        out.append('<g>')
        out.append('<line class="ground" x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f"/>' % (X(-16), Y(31), X(48), Y(31)))
        out.append('<rect class="bx body" x="%.1f" y="%.1f" width="%.1f" height="%.1f"/>' % (X(BODY[1]), Y(BODY[3]), (BODY[0] - BODY[1]) * k, (BODY[2] - BODY[3]) * k))
        out.append('<rect class="bx %s" x="%.1f" y="%.1f" width="%.1f" height="%.1f"><title>%s: R %d, L %d, B %d, T %d</title></rect>' % ("grab" if grab else "atk", X(L), Y(T), (R - L) * k, (Bb - T) * k, esc(name), R, L, Bb, T))
        out.append('<text class="lab" x="%.1f" y="%.1f">%s</text>' % (cx + 6, cy + ch - 56, esc(name)))
        out.append('<text class="sub" x="%.1f" y="%.1f">reach %d, height %d</text>' % (cx + 6, cy + ch - 38, R, Bb - T))
        out.append('<text class="sub" x="%.1f" y="%.1f">%s</text>' % (cx + 6, cy + ch - 22, esc(act)))
        out.append('</g>')
    w, h = cols * cw, 2 * ch
    return '<svg class="moves" viewBox="0 0 %d %d" role="img" aria-label="Attack boxes of the player\'s moves drawn to scale against the body box">%s</svg>' % (w, h, "".join(out))

def lanes_svg():
    # y axis: enemy y minus player y; bands per $2438a: A (-$20, +$60], B > +$60, C <= -$20; x: |dx| in 16 buckets of 16 px up to $100
    W, H = 760, 250; k = 1.15
    px = 40; py = 125
    out = ['<line class="ground" x1="%d" y1="%d" x2="%d" y2="%d"/>' % (px, py, W - 10, py)]
    def Y(dy): return py + dy * k
    bands = [("C", -0x80, -0x20, "enemy more than $20 above you"), ("A", -0x20, 0x60, "same lane: from $20 above to $60 below"), ("B", 0x60, 0xA0, "enemy more than $60 below you")]
    for case, a, b, txt in bands:
        out.append('<rect class="band band%s" x="%d" y="%.1f" width="%d" height="%.1f"/>' % (case, px + 22, Y(a), W - px - 32, (b - a) * k))
        out.append('<text class="lab" x="%d" y="%.1f">%s</text>' % (px + 32, Y(a) + 17, "table " + case))
        out.append('<text class="sub" x="%d" y="%.1f">%s</text>' % (px + 92, Y(a) + 17, txt))
    out.append('<rect class="bx body" x="%d" y="%.1f" width="%.1f" height="%.1f"/>' % (px - 8 * 0 - 8, Y(-32), 15 * k * 1.0, 63 * k))
    out.append('<text class="sub" x="%d" y="%.1f" text-anchor="start">you</text>' % (px - 8, Y(-32) - 5))
    # distance ruler
    x0 = px + 40; step = (W - px - 40 - 20) / 16
    for i in range(17):
        out.append('<line class="tick" x1="%.1f" y1="%d" x2="%.1f" y2="%d"/>' % (x0 + i * step, H - 34, x0 + i * step, H - 28))
    for i in (0, 4, 8, 12, 16):
        out.append('<text class="sub" text-anchor="middle" x="%.1f" y="%d">%s</text>' % (x0 + i * step, H - 14, "$%02x" % (i * 16) if i < 16 else "$100"))
    out.append('<text class="sub" x="%d" y="%d">horizontal distance |dx| in 16 buckets of $10 px; at $100 and beyond the enemy just walks (state 7)</text>' % (x0, H - 44))
    return '<svg class="lanes" viewBox="0 0 %d %d" role="img" aria-label="The three vertical relations the enemy brain distinguishes">%s</svg>' % (W, H, "".join(out))

def brain_svg(rows):
    cw, gap = 38, 3; lw = 190; rh = 66; sh = 15
    W = lw + 16 * (cw + gap) + 4
    out = []; y = 0
    for r in rows:
        out.append('<text class="lab" x="0" y="%d">%s</text>' % (y + 18, esc(r["name"])))
        out.append('<text class="sub" x="0" y="%d">type %d, %s</text>' % (y + 33, r["type"], esc(r["where"])))
        # case A: stacked bars, 48 px tall
        for c in r["rows"]["A"]:
            x = lw + c["b"] * (cw + gap); yy = y + 52; hh = 48; acc = 0.0
            tip = "dx $%02x-$%02x: " % (c["b"] * 16, c["b"] * 16 + 15) + "; ".join(c["detail"]) + ("" if not c["gated"] else " (decided when the animation ends)")
            out.append('<g class="cell" data-tip="%s">' % esc(tip))
            out.append('<rect class="hit" x="%d" y="%d" width="%d" height="%d"/>' % (x, yy, cw, hh))
            for g in GCOL:
                v = c["g"][g]
                if v <= 0.0001: continue
                hpx = v * hh
                out.append('<rect class="seg g-%s" x="%d" y="%.2f" width="%d" height="%.2f"/>' % (g, x, yy + hh - acc * hh - hpx + (1 if v < 1 else 0) * 0.0, cw, max(hpx - (1.5 if v < 1 else 0), 0.6)))
                acc += v
            if not c["gated"]: out.append('<circle class="now" cx="%d" cy="%d" r="2.6"/>' % (x + cw / 2, yy + hh + 8))
            out.append('</g>')
        # cases B and C: two thin strips showing the dominant group
        for j, case in enumerate("BC"):
            for c in r["rows"][case]:
                x = lw + c["b"] * (cw + gap); yy = y + 52 + 48 + 12 + j * (sh + 3)
                tip = "table %s, dx $%02x-$%02x: " % (case, c["b"] * 16, c["b"] * 16 + 15) + "; ".join(c["detail"])
                out.append('<g class="cell" data-tip="%s"><rect class="hit" x="%d" y="%d" width="%d" height="%d"/>' % (esc(tip), x, yy, cw, sh))
                acc = 0.0
                for g in GCOL:
                    v = c["g"][g]
                    if v <= 0.0001: continue
                    out.append('<rect class="seg g-%s" x="%.2f" y="%d" width="%.2f" height="%d"/>' % (g, x + acc * cw, yy, max(v * cw - (1 if v < 1 else 0), 0.6), sh))
                    acc += v
                out.append('</g>')
            out.append('<text class="sub" text-anchor="end" x="%d" y="%d">table %s</text>' % (lw - 8, y + 52 + 48 + 12 + j * (sh + 3) + 12, case))
        out.append('<text class="sub" text-anchor="end" x="%d" y="%d">table A, player idle</text>' % (lw - 8, y + 52 + 28))
        y += 52 + 48 + 12 + 2 * (sh + 3) + 26
    # bucket axis
    for i in range(0, 16, 3):
        out.append('<text class="sub" text-anchor="middle" x="%d" y="%d">$%02x</text>' % (lw + i * (cw + gap) + cw / 2, y + 8, i * 16))
    out.append('<text class="sub" x="%d" y="%d">distance |dx|</text>' % (lw, y + 26))
    return '<svg class="brain" viewBox="0 0 %d %d" role="img" aria-label="Probability of each enemy decision by distance, for four enemy types">%s</svg>' % (W, y + 34, "".join(out))

def damage_svg(rows):
    W, H = 760, 262; lx, rx = 96, 744; top = 24
    vmax = 66.0
    def X(v): return lx + (rx - lx) * v / vmax
    out = []
    for v in range(0, 65, 8):
        out.append('<line class="grid" x1="%.1f" y1="%d" x2="%.1f" y2="%d"/>' % (X(v), top, X(v), H - 36))
        out.append('<text class="sub" text-anchor="middle" x="%.1f" y="%d">%d</text>' % (X(v), H - 20, v))
    out.append('<text class="sub" x="%.1f" y="%d" text-anchor="end">damage per hit, health points</text>' % (rx, H - 4))
    out.append('<line class="full" x1="%.1f" y1="%d" x2="%.1f" y2="%d"/>' % (X(56), top - 6, X(56), H - 36))
    out.append('<text class="lab" x="%.1f" y="%d" text-anchor="end">full health, 56</text>' % (X(56) - 6, top + 2))
    levels = [("easy", "Easy"), ("normal", "Normal"), ("hard", "Hard"), ("hardest", "Hardest")]
    for i, (key, lab) in enumerate(levels):
        y = top + 28 + i * 48
        out.append('<text class="lab" x="0" y="%d">%s</text>' % (y + 4, lab))
        out.append('<line class="axis" x1="%.1f" y1="%d" x2="%.1f" y2="%d"/>' % (lx, y, rx, y))
        vals = {}
        for r in rows: vals.setdefault(r[key], []).append(r["c"])
        for v, cs in sorted(vals.items()):
            rad = 5.5 + 2.4 * (len(cs) ** 0.5 - 1) + 1.5
            out.append('<g class="cell" data-tip="%s"><circle class="dot %s" cx="%.1f" cy="%d" r="%.1f"/>' % (esc("%s, %d damage: attack types %s" % (lab, v, ", ".join("C%d" % c for c in cs))), "big" if v >= 56 else "", X(v), y, rad))
            if len(cs) > 1: out.append('<text class="cnt" text-anchor="middle" x="%.1f" y="%d">%d</text>' % (X(v), y + 4, len(cs)))
            out.append('</g>')
    return '<svg class="damage" viewBox="0 0 %d %d" role="img" aria-label="Damage of the 44 enemy attack types on each difficulty">%s</svg>' % (W, H, "".join(out))

def boss_svg():
    W = 760; rh = 30; top = 8; lx = 210; rx = 740; vmax = 50.0
    def X(v): return lx + (rx - lx) * v / vmax
    H = top + len(BOSSES) * rh + 34
    out = []
    for v in range(0, 49, 8):
        out.append('<line class="grid" x1="%.1f" y1="%d" x2="%.1f" y2="%d"/>' % (X(v), top, X(v), H - 26))
        out.append('<text class="sub" text-anchor="middle" x="%.1f" y="%d">%d</text>' % (X(v), H - 10, v))
    for i, (name, where, hp, src) in enumerate(BOSSES):
        y = top + i * rh
        out.append('<text class="lab" x="0" y="%d">%s</text><text class="sub" x="0" y="%d">%s</text>' % (y + 13, esc(name), y + 25, esc(where)))
        out.append('<rect class="bar" x="%.1f" y="%d" width="%.1f" height="14" rx="3"><title>%s: %d health, %d jab hits, %d thrown-prop hits (%s)</title></rect>' % (lx, y + 5, X(hp) - lx, esc(name), hp, hp, -(-hp // 4), esc(src)))
        out.append('<text class="val" x="%.1f" y="%d">%d</text>' % (X(hp) + 6, y + 17, hp))
    return '<svg class="bosses" viewBox="0 0 %d %d" role="img" aria-label="Health of the bosses measured in jab hits">%s</svg>' % (W, H, "".join(out))

# ---------------------------------------------------------------- page
def nat_rows():
    if not NATURAL: return ""
    out = ["<tr><th>Level</th><th>Natural run</th><th>Reached</th><th>What the bot had to learn</th></tr>"]
    for r in NATURAL:
        out.append("<tr><td>%s</td><td><span class=\"pill %s\">%s</span></td><td>%s</td><td>%s</td></tr>" % (esc(r["level"]), esc(r["cls"]), esc(r["status"]), esc(r["reached"]), esc(r["notes"])))
    return "".join(out)

def build():
    rows = brain_rows()
    dmg = damage_table()
    img1 = embed("box_01342.png"); img2 = embed("box_02097.png")
    css = open(os.path.join(HERE, "style.css")).read()
    js = open(os.path.join(HERE, "page.js")).read()
    tpl = open(os.path.join(HERE, "page.html")).read()
    import re
    tpl = re.sub(r"`([^`]+)`", r"<code>\1</code>", tpl)
    legend = "".join('<span class="key"><i class="sw g-%s"></i>%s</span>' % (g, esc(GLABEL[g])) for g in GCOL)
    page = (tpl.replace("{{CSS}}", css).replace("{{JS}}", js).replace("{{IMG1}}", img1).replace("{{IMG2}}", img2)
            .replace("{{MOVES}}", moves_svg()).replace("{{LANES}}", lanes_svg()).replace("{{BRAIN}}", brain_svg(rows)).replace("{{BRAINLEGEND}}", legend)
            .replace("{{DAMAGE}}", damage_svg(dmg)).replace("{{BOSSES}}", boss_svg()).replace("{{NATROWS}}", nat_rows()))
    out = os.path.join(BASE, "crudebuster_hitboxes_and_ai.html")
    # the repo copy is a complete document; the Artifact tool wraps the fragment itself (ARTIFACT_FRAGMENT)
    wrapped = '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"></head><body>' + page + '</body></html>'
    open(out, "w").write(wrapped)
    frag = os.environ.get("ARTIFACT_FRAGMENT")
    if frag: open(frag, "w").write(page)
    # numbers used in the prose, printed so the text can be checked against the data
    big = [(r["c"], r["hard"], r["hardest"]) for r in dmg if r["hard"] >= 56 or r["hardest"] >= 56]
    print("wrote", out, len(page) // 1024, "KiB; C types at or above 56:", big)
    print("normal damage values:", sorted(set(r["normal"] for r in dmg)))

if __name__ == "__main__":
    build()
