"""strings_dump.py: every string of the four text engines of the 68000 program, with its address (writes strings.md next to world.md).
$1c8a  65 strings, bytes = ASCII (tile index = ASCII), words $ffff end / $fffe next record (table $1cce)
$5878  19 entries, bytes ASCII, $ff end / $fe next record + 1 pad byte (table $5930), typewriter 1 char per 4 frames
$3370  24 entries, WORD codes, 2x2-tile glyphs; attr $e000 = red 'logo' font (letter = $b4 + 4*(c-'A'), digit $8c + 4*d, $b5c/$a38 '.'),
       attr $d000 = painted per-text font (glyph ids numbered by first appearance: shown as ids, not transcribed), typewriter 1 glyph per 8 frames
$28fa  80 entries, WORD codes, same 2x2 big font, instant (table $2962)
"""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from cbrom import *
import text1c8a_mod as t1, text5878 as t5, text3370 as t3, text28fa as t2
out = []
w = out.append
w("# Crude Buster (cbuster set): every string of the 68000 program\n")
w("Generated by `py/strings_dump.py` from the decrypted image. Addresses are 68000 addresses; `dst` is the text-layer RAM address (chip 0 playfield 1, 64 columns, 2 bytes per cell: column = (dst-$a0000)/2 mod 64... see world.md); `attr` is the tile attribute word ORed into every code (palette).\n")
w("## `$1c8a` instant ASCII writer (65 strings, table `$1cce`)\n")
w("Code 0 prints a blank; codes $60-$63, $64-$69, $71 are icon tiles (not letters).\n")
w("| id | addr | attr | dst | text |\n|---|---|---|---|---|")
for i, p, recs in t1.res:
    for k, (attr, dst, codes) in enumerate(recs):
        txt = "".join(chr(c) if 32 <= c < 127 else ("." if c == 0 else "<%02x>" % c) for c in codes)
        w("| %d%s | $%x | $%04x | $%x | `%s` |" % (i, "" if k == 0 else "." + str(k), p, attr, dst, txt))
w("\nIds 31-40 are field labels of a service/debug display (`BK1YPS` ... `P2XPOS`); they are written only at `$190a-$1942` inside the block `$18ce-$1946`, for which the linear listing has no direct caller (`$18cc` is a lone `rts`). Ids 41-49 are screen names (`WARNING`, `DECO MARK`, `OPENING DEMO 1`, `TITLE`, `IDOL`, `BEST PLAYERS`, `START DEMO`, `OPENING DEMO 2/3`) and have no immediate-D7 caller either; both groups are therefore *not seen in play* (inferred: left-over developer screens).\n")
w("## `$5878` typewriter, ASCII (19 entries, table `$5930`)\n")
w("Byte 0 inside a line is a pause cell. Entries 0/1 and 5/6 are the same string (the second copy is the continuation entry used by the next state).\n")
w("| id | addr | attr | dst | text |\n|---|---|---|---|---|")
for i, p, recs in t5.res:
    for k, (attr, dst, ln) in enumerate(recs):
        txt = "".join(chr(c) if 32 <= c < 127 else "." for c in ln)
        w("| %d%s | $%x | $%04x | $%x | `%s` |" % (i, "" if k == 0 else "." + str(k), p, attr, dst, txt))
w("\n## `$3370` typewriter, 2x2-tile glyphs (24 entries, table `$3456`)\n")
w("Callers (immediate D7 found by `py/d7callers.py`): 0 `$4bd2`, 3 `$4e14`, 5 `$4f4e`, 9 `$5162`, 12 `$0a1a`, 13 `$0a48`, 14 `$6040` (10 and 11 reach `$0a1a` by `$9f8`/`$a04`). Entries with attr $e000 are decoded with the logo font; $d000 entries are glyph ids.\n")
w("| id | addr | attr | dst | text |\n|---|---|---|---|---|")
for i, p, lines in t3.res:
    for k, (a, d, cs) in enumerate(lines):
        if a == 0xe000: txt = "`" + "".join(t2.big(c) for c in cs).replace("<83c>", " ") + "`"
        else: txt = "ids " + " ".join("%x" % c for c in cs)
        w("| %d%s | $%x | $%04x | $%x | %s |" % (i, "" if k == 0 else "." + str(k), p, a, d, txt))
w("\n## `$28fa` instant big-font writer (80 entries, table `$2962`)\n")
w("Entries 36-49, 50-58 and 69-78 use graphic tiles (ids shown); 0-9 are the digits 0-9, 11-16 digits 1-6 (stage number), 17 `STAGE`, 18 `CONGRATULATION`, 19 `GAME OVER`, 10 and 22 menus.\n")
w("| id | addr | attr | dst | text |\n|---|---|---|---|---|")
for i, p, recs in t2.res:
    for k, (a, d, cs) in enumerate(recs):
        txt = "".join(t2.big(c) for c in cs)
        w("| %d%s | $%x | $%04x | $%x | `%s` |" % (i, "" if k == 0 else "." + str(k), p, a, d, txt))
w("\n## Other text data\n")
w("- Best-scores initial names at `$6c6c` (3 bytes + 0 each): " + ", ".join(repr(bytes(ROM[0x6c6c + 4*i: 0x6c6c + 4*i + 3]).decode()) for i in range(10)) + "; initial scores at `$6c44`: " + ", ".join("%08x" % L(0x6c44 + 4*i) for i in range(10)) + ".")
w("- Name-entry character table `$7fba` (42 chars): `%s`." % bytes(ROM[0x7fba:0x7fba+42]).decode())
w("- Digit/space map for `$1ab2` numbers `$1b3a`: `%s`." % " ".join("%02x" % B(0x1b3a + i) for i in range(16)))
open(os.path.join(os.path.dirname(__file__), "..", "strings.md"), "w").write("\n".join(out) + "\n")
print("strings.md written,", len(out), "lines")
